#! /bin/sh

feh --bg-fill ~/Pictures/wallpapers/wall-01.webp
bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width 1
bspc config border_radius 8
bspc config window_gap 5

bspc config split_ratio 0.52
bspc config borderless_monocle false
bspc config gapless_monocle true

bspc config normal_border_color "#00000000"
bspc config focused_border_color "#00fa5c"

# Launch sxhkd
pkill -x sxhkd
pgrep -x sxhkd >/dev/null || sxhkd -c "$HOME/.config/bspwm/sxhkdrc" &
pkill picom
picom &

#Launch polybar
./.config/polybar/blocks/launch.sh
